# Application bindings
bindd = SUPER ALT, RETURN, Tmux, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)" tmux new
$terminal = uwsm app -- $TERMINAL
$browser = omarchy-launch-browser

bindd = SUPER, RETURN, Terminal, exec, $terminal --dir="$(omarchy-cmd-terminal-cwd)"
bindd = SUPER SHIFT, RETURN, Browser, exec, omarchy-launch-browser
bindd = SUPER SHIFT, F, File manager, exec, uwsm app -- nautilus --new-window
bindd = SUPER SHIFT, B, Browser, exec, $browser
bindd = SUPER SHIFT ALT, B, Browser (private), exec, $browser --private
bindd = SUPER SHIFT, N, Editor, exec, omarchy-launch-editor
bindd = SUPER SHIFT, T, Activity, exec, omarchy-launch-tui btop
bindd = SUPER SHIFT, D, Docker, exec, omarchy-launch-tui lazydocker
bindd = SUPER SHIFT, O, Obsidian, exec, omarchy-launch-or-focus obsidian "uwsm app -- obsidian -disable-gpu --enable-wayland-ime"

# If your web app url contains #, type it as ## to prevent hyperland treat it as comments
bindd = SUPER SHIFT, Y, YouTube, exec, omarchy-launch-or-focus-webapp YouTube "https://youtube.com/"

# Overwrite existing bindings, like putting Omarchy Menu on Super + Space
# unbind = SUPER SHIFT, SPACE
# bindd = SUPER SHIFT, SPACE, Omarchy menu, exec, omarchy-menu

# Custom

# Minimize window (Only works for 1 window)
bind = SUPER SHIFT, S, togglespecialworkspace, magic
bind = SUPER SHIFT, S, movetoworkspace, +0
bind = SUPER SHIFT, S, togglespecialworkspace, magic
bind = SUPER SHIFT, S, movetoworkspace, special:magic
bind = SUPER SHIFT, S, togglespecialworkspace, magic

# Volume control
bindd = SUPER, bracketright, Volume Up, exec, pactl set-sink-volume @DEFAULT_SINK@ +5%
bindd = SUPER, bracketleft, Volume Down, exec, pactl set-sink-volume @DEFAULT_SINK@ -5%
bindd = SUPER, M, Volume Mute, exec, pactl set-sink-mute @DEFAULT_SINK@ toggle

# Zoom util for screen recording
# https://github.com/FShou/hypr-zoom
bind = SUPER, Z, exec, ~/utils/hypr-zoom/hypr-zoom -easing=InOutQuad -target=1.8 -duration=200
